[versions]

accompanistPagerIndicators = "0.24.2-alpha"
activity-compose = "1.7.2"
androidx-test-ext-junit = "1.1.5"
androidx-lifecycle = "2.6.1"
accompanist = "0.30.1"

charts = "0.2.4-alpha"
core = "1.9.51"
core-ktx = "1.10.1"
compose-bom = "2023.06.01"
coreSplashscreen = "1.0.1"
coroutines = "1.7.1"
datastore = "1.0.0"
icon-extended = "1.5.0-rc01"

data-store = "1.0.0"

detektGradlePlugin = "1.23.0"
espresso-core = "3.5.1"


google-Truth= "1.1.3"

hilt = "2.48"
dagger-hilt = "2.48"
hilt-navigation = "1.0.0"

junit = "4.13.2"

kotlin = "1.9.0"
kotlinter = "3.14.0"
kotlinxCollectionsImmutable = "0.3.5"
kotlinxSerializationJson = "1.4.1"


lifecycle-runtime-ktx = "2.6.1"
leakCanary = "2.11"

lottieCompose = "4.0.0"
moshi = "1.15.0"
mock-library = "1.13.4"
material2 = "1.4.3"

navigation = "2.6.0"

retrofit = "2.9.0"
room = "2.5.2"

splashscreen ="1.0.1"

turbine = "1.0.0"

viewmodel = "2.6.1"
kover ="0.7.2"




[libraries]
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPagerIndicators" }
androidx-core-splashscreen-v100 = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
charts = { module = "com.github.tehras:charts", version.ref = "charts" }
core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "core" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "core" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
splashscreen = { group ="androidx.core", name = "core-splashscreen", version.ref="splashscreen"}

androidx-lifecycle = { group ="androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref ="androidx-lifecycle"}
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
datastorelib = { group ="androidx.datastore" ,name ="datastore-preferences", version.ref ="data-store"}


compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
coroutine-test = { group= "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test",version.ref = "coroutines"}
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektGradlePlugin" }

espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

googleTruth = { group ="com.google.truth", name ="truth", version.ref = "google-Truth" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-nav = { group = "androidx.hilt" , name ="hilt-navigation-compose", version.ref = "hilt-navigation" }

iconextended = {group="androidx.compose.material",name ="material-icons-extended-android", version.ref="icon-extended"}

junit = { group = "junit", name = "junit", version.ref = "junit" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }


material3 = { group = "androidx.compose.material3", name = "material3" }
material2 ={ group =  "androidx.compose.material", name ="material", version.ref = "material2"}
mock-library = { group = "io.mockk", name = "mockk", version.ref = "mock-library"}

navigation-library = { group ="androidx.navigation", name ="navigation-compose", version.ref ="navigation"}

ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

square-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
square-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
square-moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
square-retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit"}

turbine = { group = "app.cash.turbine", name = "turbine" , version.ref = "turbine"}

viewmodel-lifecycle = { group ="androidx.lifecycle", name ="lifecycle-viewmodel-compose",version.ref="viewmodel" }


[plugins]
androidApplication = { id = "com.android.application", version = "8.0.2" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android",version.ref = "dagger-hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt",version.ref = "detektGradlePlugin" }
kolinter = { id ="org.jmailen.kotlinter",  version.ref ="kotlinter" }
kover = {id="org.jetbrains.kotlinx.kover", version.ref= "kover"}


[bundles]

